version: '3.8'

services:
  certbot:
    image: certbot/certbot:latest
    container_name: certbot-temp
    volumes:
      - ../nginx/etc_nginx/certbot/www:/var/www/certbot
      - ../nginx/etc_nginx/certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh
    networks:
      - nginx_network  # nginx에서 이미 사용 중인 네트워크를 재활용

networks:
  nginx_network:
    external: true
