version: '3.8'

services:
  # PostgreSQL
  harbor-db:
    image: postgres:13
    container_name: harbor-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: harbor123
      POSTGRES_DB: registry
    volumes:
      - ./harbor-db-data:/var/lib/postgresql/data
    networks:
      - nginx_network

  # Redis
  redis:
    image: redis:6
    container_name: harbor-redis
    restart: always
    volumes:
      - ./harbor-redis-data:/data
    networks:
      - nginx_network

  # Harbor Core
  harbor-core:
    image: goharbor/harbor-core:v2.10.0
    container_name: harbor-core
    restart: always
    depends_on:
      - harbor-db
      - redis
    environment:
      CORE_SECRET: core123
      JOBSERVICE_SECRET: job123
      POSTGRES_PASSWORD: harbor123
      POSTGRES_USER: postgres
      POSTGRES_DB: registry
      REDIS_URL: redis://redis:6379
    volumes:
      - ./harbor-config:/etc/harbor       # Harbor 구성 파일
      - ../nginx/etc_nginx/certbot/conf/live:/etc/harbor/ssl      # SSL 인증서
      - ./harbor-logs:/var/log/harbor     # 로그
    networks:
      - nginx_network

  # Harbor JobService
  harbor-jobservice:
    image: goharbor/harbor-jobservice:v2.10.0
    container_name: harbor-jobservice
    restart: always
    depends_on:
      - harbor-core
    environment:
      JOBSERVICE_SECRET: job123
    volumes:
      - ./harbor-logs:/var/log/harbor     # Core와 동일 로그 공유
    networks:
      - nginx_network

  # Harbor Portal
  harbor-portal:
    image: goharbor/harbor-portal:v2.10.0
    container_name: harbor-portal
    restart: always
    depends_on:
      - harbor-core
    networks:
      - nginx_network

  # Harbor Registry
  harbor-registry:
    image: goharbor/registry-photon:v2.10.0
    container_name: harbor-registry
    restart: always
    networks:
      - nginx_network
    volumes:
      - ./registry-data:/var/lib/registry

networks:
  nginx_network:
    external: true
